name: Store and Print Environment Variable

on:
  push:
    branches:
      - master

jobs:
  store-variable:
    runs-on: ubuntu-latest

    steps:
    - name: Set GitHub Environment Variable
      run: echo "MY_ENV_VARIABLE=my_value" >> $GITHUB_ENV
  
    - name: Display Environment Variable (Windows)
      run: |
        echo "GitHub environment variable MY_ENV_VARIABLE is: $MY_ENV_VARIABLE"
