name: Store Hashtable as Environment Variable

on:
  push:
    branches:
      - master

jobs:
  store_hashtable:
    runs-on: windows-latest

    steps:
    - name: Set Hashtable as Environment Variable
      shell: pwsh
      run: |
        $myHashtable = @{
          key1 = 'value1'
          key2 = 'value2'
        }
        $myHashtableJson = $myHashtable | ConvertTo-Json
        Write-Host "MY_HASHTABLE=$myHashtableJson" >> $GITHUB_ENV

    - name: Use Hashtable from Environment Variable
      shell: pwsh
      run: |
        $myHashtableJson = $env:MY_HASHTABLE
        $myHashtableJson
        $myHashtable = $myHashtableJson | ConvertFrom-Json
        Write-Host "Hashtable key1: $($myHashtable.key1)"
        Write-Host "Hashtable key2: $($myHashtable.key2)"
