name: Set JSON as Variable1 (Windows)

on:
  push:
    branches:
      - master

jobs:
  set_json_variable:
    runs-on: windows-latest

    steps:
    - name: Set JSON as Variable
      id: set-json
      shell: powershell
      run: |
        # Your JSON string here
        $Output = New-Object -TypeName Hashtable
        $Output.workspaceName = "az"
        $Output.businessCommonVNetName = "vn"
        $Output.businessCommonVNetCIDR = "192"
        $Output
        $a= $Output | convertto-json
        $b=$Output |convertfrom-json
        echo "##vso[task.setvariable variable=my_json;isOutput=true]$Output"
        echo "##vso[task.setvariable variable=my_json1;isOutput=true]$a"
        echo "##vso[task.setvariable variable=my_json2;isOutput=true]$b"
        $c=1234
        echo "##vso[task.setvariable variable=my_json3;isOutput=true]$c"
        echo "action_state=$b" | Out-File -FilePath $env:GITHUB_ENV -Append
        
              
        
    - name: Use JSON Variable
      shell: powershell
      run: |
        # Access the JSON variable from the previous step
        $myJson3 = "${{ env.action_state }} "
        Write-Host "JSON variable value: $myJson3"
        echo "${{ env.action_state }}" # This will output 'yellow'



    - name: Parse JSON
      shell: powershell
      run: |
       ./1.ps1 -outputsummary "${{ env.action_state }}"
