name: Store and Print Environment Variable

on:
  push:
    branches:
      - master

jobs:
  store-variable:
    runs-on: windows-latest

    steps:
    - name: Set GitHub Environment Variable
      shell: pwsh
      run: |
         write-host "MY_ENV_VARIABLE=my_value" >> $GITHUB_ENV
  
    - name: Display Environment Variable (Windows)
      shell: pwsh
      run: |
        write-host "GitHub environment variable MY_ENV_VARIABLE is: $MY_ENV_VARIABLE"
